/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory;

import DAO.Connect;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.sql.*;
import java.util.Date;
import javax.swing.JOptionPane;


/**
 *
 * @author DELL
 */
public class UpdateProducts extends javax.swing.JFrame {

    public String numberPattern = "^[0-9]*$";
    /**
     * Creates new form UpdateProducts
     */
    public UpdateProducts() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtProductId = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPricePerUnit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dateManufacturingDate = new com.toedter.calendar.JDateChooser();
        dateExpiryDate = new com.toedter.calendar.JDateChooser();
        jButton8 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtAddQuantity = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Update Products");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 316, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("Add Products");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 13, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setText("View Products");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 13, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton4.setText("Update Products");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 13, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton5.setText("Sales and Billing");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 13, -1, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton6.setText("View Bills");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 13, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 118, 1200, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Product Id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));
        getContentPane().add(txtProductId, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 300, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search.png"))); // NOI18N
        jButton7.setText("Search");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 236, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Quantity");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));
        getContentPane().add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 236, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Price Per Unit");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, -1, -1));
        getContentPane().add(txtPricePerUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 236, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Manufacturing Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Expiry Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, -1, 20));
        getContentPane().add(dateManufacturingDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 236, -1));
        getContentPane().add(dateExpiryDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 236, -1));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/save.png"))); // NOI18N
        jButton8.setText("Update and Save");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 610, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Add Quantity");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));
        getContentPane().add(txtAddQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int checkProductExist=0;// -> code ?? logic??
        String uniqueId = txtProductId.getText();
        if(uniqueId.equals("")){
            JOptionPane.showMessageDialog(null, "Product Id is required!!!");
        }
        else{
                SimpleDateFormat dFormat= new SimpleDateFormat("dd-MM-yyyy"); 
            try{
                Connection con = Connect.getCon();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("select *from product where uniqueId="+uniqueId+"");
                
                while(rs.next()){
                    txtProductId.setEditable(false);
                    txtName.setText(rs.getString("name"));
                    txtQuantity.setText(rs.getString("quantity"));
                    txtPricePerUnit.setText(rs.getString("price"));
                    String Manufacturing_date = rs.getString("Manufacturing_date");
                    String expiry_date = rs.getString("expiry_date");
                    if(Manufacturing_date !=""){
                        try{
                            dateManufacturingDate.setDate(dFormat.parse(Manufacturing_date));
                        }
                        catch(Exception e){
                        }
                    }
                    if(expiry_date !=""){
                        try{
                            dateExpiryDate.setDate(dFormat.parse(expiry_date));
                        }
                        catch(Exception e){
                        }
                    }
                    checkProductExist=1;
                }
                
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            if(checkProductExist == 0){
                JOptionPane.showMessageDialog(null, "Product Id does not exist");
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new AddProducts().setVisible(true);
          setVisible(false);       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         new ViewProducts().setVisible(true);
            setVisible(false);   
    }//GEN-LAST:event_jButton3ActionPerformed

      private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
         new Sales().setVisible(true);
            setVisible(false);   
      }
      
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dFormat= new SimpleDateFormat("dd-MM-yyyy"); 
        String uniqueId = txtProductId.getText();
        String name = txtName.getText();
        String quantity = txtQuantity.getText();
        String price = txtPricePerUnit.getText();
        String addQuantity = txtAddQuantity.getText();
        
        int totalQuantity;
        totalQuantity = 0;
        if(addQuantity.equals("")){
            totalQuantity = Integer.parseInt(quantity);
        }else{
            totalQuantity = Integer.parseInt(quantity) + Integer.parseInt(addQuantity);
        }
        
                Date Manufacturing_date= dateManufacturingDate.getDate();
        Date expiry_date= dateExpiryDate.getDate();
        String manufacturing_date="";
         String Expiry_date="";
         if(Manufacturing_date != null){
               manufacturing_date=dFormat.format(dateManufacturingDate.getDate());
         }
          if(expiry_date!=null){
               Expiry_date=dFormat.format(dateExpiryDate.getDate());
              }
          if(uniqueId.equals("")){
           JOptionPane.showMessageDialog(null, "Product ID is required");
           }else if(name.equals("")){
               JOptionPane.showMessageDialog(null, "Name is required");
           }else if(quantity.equals("")){
               JOptionPane.showMessageDialog(null, "Quantity is required");
            }else if(!addQuantity.matches(numberPattern)){
              JOptionPane.showMessageDialog(null, "Quantity is Invalid");
           }else if(price.equals("")){
               JOptionPane.showMessageDialog(null, "Price Per Unit is required");
           }else if(!price.matches(numberPattern)){
              JOptionPane.showMessageDialog(null, "Price Per Unit is Invalid"); 
           }else if(Manufacturing_date.equals("")){
               JOptionPane.showMessageDialog(null, "Manufacturing Date is required");
           }else if(expiry_date.equals("")){
                JOptionPane.showMessageDialog(null, "Expiry Date is required");
           }else{ 
                    try{
                        Connection con = Connect.getCon();
                        PreparedStatement ps = con.prepareStatement(" update product set name=?,quantity = ?,price =?, Manufacturing_date = ?,expiry_date = ? where uniqueId = ?");
                  
                   ps.setString(1, name);
                   ps.setInt(2, totalQuantity );
                   ps.setString(3, price);
                   ps.setString(4, manufacturing_date);
                   ps.setString(5, Expiry_date);
                    ps.setInt(6, Integer.parseInt(uniqueId));
                   ps.executeUpdate();
                   JOptionPane.showMessageDialog(null, "Product Updated Successfully");
                   setVisible(false);
                    new UpdateProducts().setVisible(true);            
                    }
                    catch(Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    }
    }//GEN-LAST:event_jButton8ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateExpiryDate;
    private com.toedter.calendar.JDateChooser dateManufacturingDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtAddQuantity;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPricePerUnit;
    private javax.swing.JTextField txtProductId;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
