/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory;

import DAO.Connect;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author DELL
 */
public class ViewProducts extends javax.swing.JFrame {

    /**
     * Creates new form viewMedicine
     */
    public ViewProducts() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        btnCheckStock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("View Products");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 124, 1200, 10));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Product Id", "Name", "Qunatity", "Price Per Unit", "Manufacturing date", "Expiry date"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 1170, 280));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setText("Add Products");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 13, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton4.setText("View Products");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 13, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton5.setText("Update Products");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 13, -1, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton6.setText("Sales and Billing");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 13, -1, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton7.setText("View Bill");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 15, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("CLICK ON ROW TO DELETE THE PRODUCT");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 720, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Quantity", "Expiry Date" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 150, -1));

        jLabel2.setText("Search By:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 70, -1));

        txtMessage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMessageActionPerformed(evt);
            }
        });
        getContentPane().add(txtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 1160, 120));

        btnCheckStock.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnCheckStock.setText("Check Stock");
        btnCheckStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckStockActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheckStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 490, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new AddProducts().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new UpdateProducts().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try {
            Connection con = Connect.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from product "); // => select * from product order by ______esmai lekhne ho??  just test..
            /// 
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString("product_pk"), rs.getString("uniqueId"), rs.getString("name"), rs.getString("quantity"), rs.getString("price"), rs.getString("Manufacturing_date"), rs.getString("expiry_date")});//yei ho?
                // test
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String id = model.getValueAt(index, 0).toString();
        int a = JOptionPane.showConfirmDialog(null, "Do you want to delete this product", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            try {
                Connection con = Connect.getCon();
                PreparedStatement ps = con.prepareStatement("delete from product where product_pk=?");
                ps.setString(1, id);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Product Deleted Succesfully!!!");
                setVisible(false);
                new ViewProducts().setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Sales().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ViewBill().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:  

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try {
            Connection con = Connect.getCon();
            Statement st = con.createStatement();

            if (jComboBox1.getSelectedItem() == "Quantity") {
                ResultSet rs = st.executeQuery("select *from product order by quantity");

                model.setRowCount(0);//test
                while (rs.next()) {

                    model.addRow(new Object[]{rs.getString("product_pk"), rs.getString("uniqueId"), rs.getString("name"), rs.getString("quantity"), rs.getString("price"), rs.getString("Manufacturing_date"), rs.getString("expiry_date")});//yei ho?
                }
            } else {
                ResultSet rs = st.executeQuery("select *from product order by STR_TO_DATE(expiry_date,'%d-%m-%Y')"); // yesma k ho expiry date ko

                model.setRowCount(0);
                while (rs.next()) {
                    model.addRow(new Object[]{rs.getString("product_pk"), rs.getString("uniqueId"), rs.getString("name"), rs.getString("quantity"), rs.getString("price"), rs.getString("Manufacturing_date"), rs.getString("expiry_date")});
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMessageActionPerformed
        // TODO add your handling code here:
//         final int alertLimit  = 50;
//        txtMessage.setEditable(false);
//        try{
//            Connection con = Connect.getCon();
//            Statement st = con.createStatement();
//            ResultSet rs = st.executeQuery(" SELECT * FROM product ");
//            boolean alertFound = false;
//
//            while (rs.next()) {
//                int productId = rs.getInt("uniqueid");
//                String itemName = rs.getString("name");
//                int quantity = rs.getInt("quantity");
//
//                if(quantity < alertLimit ){
//                String alertMessage = "Alert: Inventory level for item " + itemName + " (ID: " + productId + ") is below the specified limit. Current quantity: " + quantity;
//                txtMessage.setText(alertMessage);
//                alertFound = true;
////                 JOptionPane.showMessageDialog(null, alertMessage, "Inventory Alert", JOptionPane.WARNING_MESSAGE);
//                    break;
//                }
//            }
//            rs.close();
//         
//            con.close();
//             if (!alertFound) {
//            txtMessage.setText(""); // Clear the text field if no alerts are found
//        }
//        }
//
//        catch(Exception e){
////           JOptionPane.showMessageDialog(null, e);
//e.printStackTrace();
//        }
    }//GEN-LAST:event_txtMessageActionPerformed

    private void btnCheckStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckStockActionPerformed
        // TODO add your handling code here:
        final int alertLimit = 50;
        txtMessage.setEditable(false);
//        StringBuilder alertMessage = new StringBuilder();
        String msg = "";
        try {
            Connection con = Connect.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(" SELECT * FROM product where quantity < 50 "); // yesma hola qurrey hera where ko
            boolean alertFound = false;

            while (rs.next()) {
                int productId = rs.getInt("uniqueID");// this one
                String itemName = rs.getString("name");// this one
                int quantity = rs.getInt("quantity");// this

                if (quantity < alertLimit) {
                    msg = " Alert: Low quantity level of product " + itemName +   "\nCurrent Quantity:" + quantity + "\n"; // .thapne + garera ?? esmai add garne ho?? maybe..
                    // add garana kun kun chahincha vane ko bujena aayena malai jun jun ko quantity level kam xa tyo product haru dekhunu parne ho
                    // ani teta \n chaldaina aba single line mai huncha
                    
                    alertFound = true;
//                alertMessage.append(Message);
                }
            }
            rs.close();

            con.close();
            if (alertFound) {
                txtMessage.setText(msg); // Display the accumulated alert messages
            } else {
                txtMessage.setText("No inventory alerts."); // Display a message if no alerts are found
            }
        } catch (Exception e) {
//           JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCheckStockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckStock;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables
}
